### ISSUE TITLE
Broken letters everything is lowercased

### ISSUE THREAD

**Issue by NXxEpicXCreeperxX** [PlaceholderAPI/PlaceholderAPI#432] opened 2020-08-10 19:57 UTC
### Issue

For some reason on PlaceholderAPI 2.10.9 everything in chat is lowercased
Is there an easy way to fix this?
no error in console and i tried resetin the folder

### How to reproduce

1.

**Comment by Andre601** [comment] 2020-08-10 20:19
Please follow the issue templates and provide the required information.

I went ahead and edited your issue. Please fill out the remaining parts yourself.

**Comment by VozikCZE** [comment] 2020-08-12 12:08
I have the same issue, messages from plugins like essentials, skript, titlemanager are fully lowercased.

This is my /papi dump: https://paste.helpch.at/obiluzewoh
![image](https://user-images.githubusercontent.com/48393384/90013268-3d09fa00-dca5-11ea-8ca8-57c5c82a4c3a.png)

**Comment by Andre601** [comment] 2020-08-13 15:30
I can't really reproduce this issue using my Shortcut expansion and the `/papi parse` command.

![image](https://cdn.discordapp.com/attachments/574554521825705994/743213737376481364/unknown.png)

And also the chat plugin I user (which supports and uses PlaceholderAPI) doesn't have this issue, so it is most likely caused by another plugin that interferes with the packets or similar.

**Comment by VozikCZE** [comment] 2020-08-13 16:07
Ok, I tried to remove ChatInjector and it works fine now. So ChatInjector is causing this issue.

**Comment by Andre601** [comment] 2020-08-13 16:15
Good to know. I would assume the author of this issue has a similar setup and since the tests I made (And the code itself) don't suggest PAPI to lowercase anything will I close this.
Feel free to respond to this, if the issue still exists without any other plugin installed.

**Closed by Andre601** 2020-08-13 16:15 UTC
Labels: Problem: More info required, Type: Issue (Unconfirmed)

**Comment by NXxEpicXCreeperxX** [comment] 2020-08-13 20:49
Will this be fixed soon?

**Comment by AzonFR** [comment] 2020-08-26 15:13
Same issue, with the latest version, everything is lowercased

**Comment by Andre601** [comment] 2020-08-26 16:15
## Before you comment, read this
This *issue* is not caused by PlaceholderAPI. The plugin parses the placeholders as expected and the returned text keeps its casing.
The issue is most likely caused by ChatInjector. If you have this plugin, remove it to fix the issue. Also let the dev know about this bug.

**Do not comment on this issue about this issue as it isn't caused by PlaceholderAPI!**

**Comment by AzonFR** [comment] 2020-08-27 13:18
Okay but why this issue only happen with the latest version of PlaceholderAPI ?
