### ISSUE TITLE
NoClassDefFoundError: com/sk89q/worldguard/WorldGuard

### ISSUE THREAD

**Issue by JGuerndt** [PlaceholderAPI/PlaceholderAPI#120] opened 2019-05-19 06:32 UTC
### Issue
The WorldGuard expansion generates an error on loading. May be related to #66 

### Expected behaviour
The expansion should load normally, without exception.

### Actual behaviour
https://gist.github.com/JGuerndt/e046277650e041a53d45c414ba060a41

### How to reproduce
1. I am not sure when this started. I downloaded the expansion several days (and have downloaded it again), but am just now trying to use one of the placeholders. 

PlaceHolderAPI - 2.10.2
WorldGuard - 6.2.2
TacoSpigot-1.12.2-Build114-f8ba67d6

**Comment by darbyjack** [comment] 2019-05-19 07:02
Duplicate of https://github.com/PlaceholderAPI/WorldGuard-Expansion/issues/2

**Closed by darbyjack** 2019-05-19 07:02 UTC
