### ISSUE TITLE
Issue with placeholder API registering placholders.

### ISSUE THREAD

**Issue by mike3132** [PlaceholderAPI/PlaceholderAPI#897] opened 2022-12-10 20:05 UTC
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

Having an issue with placeholder API registering placholders. If I manually reload the plugin with /papi reload it fixes itself

Papi version : 2.11.2
Server version : Paper 1.19.2
![Screenshot_1](https://user-images.githubusercontent.com/32972166/206873356-55183f96-5c0d-4a09-84b4-8a060e2f9dab.png)
![Screenshot_2](https://user-images.githubusercontent.com/32972166/206873358-78df6f05-34d1-43bf-9d6f-8a88642c018f.png)

### Expected Behaviour

Placeholders to work.

### How to Reproduce

Install placeholder api onto 1.19.2 server and begin adding in placeholders and then restart server. They will no longer work until you /papi reload

### `/papi dump` Output

https://paste.helpch.at/wefoqovime

### Console Log

https://paste.helpch.at/kiyuboceno.makefile

### Errors

https://paste.helpch.at/mexitawute.rb

**Comment by Andre601** [comment] 2022-12-10 21:32
This is most likely not caused by PlaceholderAPI.
The error mentions this:
> `java.util.concurrent.CompletionException: java.lang.IllegalStateException: zip file closed`

This line means that the Jar file has been closed by something while PlaceholderAPI was loading.
Usually, this is caused by either the server (see #868) or another plugin, if they happen to interact with any kind of ClassLoader.

Your best option could be to remove half the plugins and see if that fixes it. If not, repeat until you find the one causing this.

**Comment by mike3132** [comment] 2022-12-11 08:54
This seems to be happening whenever I install any type of shop plugin, 
IE: 
ChestShop > https://www.spigotmc.org/resources/chestshop.51856/
QuickShop > https://www.spigotmc.org/resources/quickshop-reremake-1-19-ready-multi-currency.62575/
InsaneShops > https://www.spigotmc.org/resources/insane-shops.67352/

**Comment by PiggyPiglet** [comment] 2022-12-11 13:25
I am not able to reproduce. I installed PAPI 2.11.2 & ChestShop 3.12.2 on paper 1.19.2-307, Temurin-17.0.3+7.

Installed the player expansion, restarted the server, and immediately parsed %player_name% once the server had started again. Placeholder parsed fine, no exceptions in console.

Does the issue happen when you have only PAPI + a shop plugin installed? Or does it happen when you have papi, all your other plugins, and a shop plugin installed?

**Comment by mike3132** [comment] 2022-12-11 18:13
So when I install QuickShop > 

I get this error in console and it breaks all of my placeholders.
https://paste.helpch.at/abitaligek.rb

**Comment by Andre601** [comment] 2024-05-19 16:19
This issue is quite outdated, so I'll close it. Should the problem still be present, reply to the issue with up-to-date information.

**Closed by Andre601** 2024-05-19 16:19 UTC
Labels: Type: Issue (Unconfirmed)
