### ISSUE TITLE
1.13.2 mysql not a work

### ISSUE THREAD

**Issue by successed** [PlaceholderAPI/PlaceholderAPI#87] opened 2019-03-10 00:51 UTC
i have latest PlaceholderAPI 2.9.2 

my server version latest 1.13.2 paperspigot.

issue:
this not a work mysql, i pasted mysql place and http://prntscr.com/mvpic4

this a not my credit. My credit is https://prnt.sc/mvpeag

this my query : query: SELECT uye_kredi FROM uyeler WHERE uye_kadi = '{player}'
my table design : https://prnt.sc/mvpeqs

**Comment by SuperRonanCraft** [comment] 2019-04-27 03:15
Hey @successed very sorry that I was not notified about this before hand, but yeah, the only reason a query could be blocked from happening is either the player does not exist on the mysql or the config is not setup correctly, could you post a copy of the custom expansion config.yml file?

**Comment by Andre601** [comment] 2019-05-04 19:39
Is this still a issue @successed ?
If not then can we close it?

I hope to hear an answer within the next week or the issue will be closed.

**Comment by successed** [comment] 2019-05-07 05:47
> Is this still a issue @successed ?
> If not then can we close it?
> 
> I hope to hear an answer within the next week or the issue will be closed.

Mysql connect is not a work.

**Comment by SuperRonanCraft** [comment] 2019-05-23 04:51
Hey @successed try out the newest version of the expansion, I do believe it fixes a bunch of caching issues in the past, it is currently on version 1.3.0
Get it here https://api.extendedclip.com/expansions/mysql/

**Comment by aBo0oDyy** [comment] 2019-06-17 01:25
Hey there,
Looks like the issue has been solved ?

I'll close the issue since the author of the expansion replied and updated the expansion to fix that.
Feel free to reopen it if the issue isn't resolved yet.

**Closed by aBo0oDyy** 2019-06-17 01:25 UTC
Labels: Type: Issue (Expansion)

**Comment by successed** [comment] 2019-06-17 09:04
yes this issue solved, ty for update, it is fixed new update..
