### ISSUE TITLE
Can't load any expansion from ecloud!!

### ISSUE THREAD

**Issue by pushuangchang** [PlaceholderAPI/PlaceholderAPI#244] opened 2020-02-15 23:15 UTC
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

The PAPI can't register any expansions I downloaded by command or even manually,no error logs appeared

### Expected behaviour
> What should PlaceholderAPI do?

It should register my Player Expansion after /papi reload

### Actual behaviour
> What does PlaceholderAPI actually do?

it says reload complete but the placeholders don't work and the expansion isn't shown in /papi list

### How to reproduce
> What steps did you made, to get this bug?

1.  use the latest Mohist server core 1.6-e408017
2.  use the PAPI 2.10.4
3. download the expansion with the command or manually
4. use the command /papi reload to reload the plugin
5. if this bug occurred the plugin should say reload complete and show no error logs but when you use /papi list it won't show the expansion you downloaded in the folder.

**Comment by Andre601** [comment] 2020-02-15 23:23
What is "Mohist server core 1.6-e408017"?
My guess is, that you're simply running a server type that isn't supported by PlaceholderAPI. Make sure to either use Spigot or PaperMC (recommended)

If that is actually a Spigot/PaperMC fork, make sure your server actually allows connections to the e-cloud located under https://api.extendedclip.com (https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/FAQ#i-cant-download-the-expansion)

In addition also check the console for any (startup) errors.

**Comment by aBooDyy** [comment] 2020-02-29 10:37
Hi @pushuangchang,

Have you tried what Andre601 said to solve your issue? Any updates?

Issue will be closed in a few days if we haven't heard from you.

**Comment by pushuangchang** [comment] 2020-03-02 02:49
It's now fixed by the server developer.
But new problems appeared:
every time after I installed an expansion the plugin can't connect to ecloud any more
no error logs too and it says no expansions are available.

**Comment by MrAureliusR** [comment] 2020-03-26 00:59
Having the exact same issue on Paper Spigot. Papi has just completely stopped working. It seems to be getting malformed JSON from the server?

[01:53:26 WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.4 generated an exception 
while executing task 22
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unt
erminated string at line 1 column 109449 path $..versions[0].version
        at com.google.gson.Gson.fromJson(Gson.java:902) ~[patched_1.15.2.jar:git-Paper-
144]
        at com.google.gson.Gson.fromJson(Gson.java:852) ~[patched_1.15.2.jar:git-Paper-
144]
        at com.google.gson.Gson.fromJson(Gson.java:801) ~[patched_1.15.2.jar:git-Paper-
144]
        at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$fetch$4(
ExpansionCloudManager.java:167) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~
[patched_1.15.2.jar:git-Paper-144]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.
java:54) ~[patched_1.15.2.jar:git-Paper-144]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerR
eportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-144]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:11
49) [?:1.8.0_242]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:6
24) [?:1.8.0_242]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1
 column 109449 path $..versions[0].version
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559) ~[patche
d_1.15.2.jar:git-Paper-144]
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1017) ~[pa
tched_1.15.2.jar:git-Paper-144]
        at com.google.gson.stream.JsonReader.nextName(JsonReader.java:787) ~[patched_1.
15.2.jar:git-Paper-144]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Refl
ectiveTypeAdapterFactory.java:215) ~[patched_1.15.2.jar:git-Paper-144]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapter
RuntimeTypeWrapper.java:41) ~[patched_1.15.2.jar:git-Paper-144]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Coll
ectionTypeAdapterFactory.java:82) ~[patched_1.15.2.jar:git-Paper-144]
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(Coll
ectionTypeAdapterFactory.java:61) ~[patched_1.15.2.jar:git-Paper-144]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(Reflective

**Comment by darbyjack** [comment] 2020-03-30 04:32
Should be fixed in the latest version.

**Closed by darbyjack** 2020-03-30 04:32 UTC
Labels: Problem: More info required
