### ISSUE TITLE
 Placeholders not working since 1.15

### ISSUE THREAD

**Issue by rosiejane** [PlaceholderAPI/PlaceholderAPI#449] opened 2020-08-26 17:38 UTC
### Issue

Ever since i updated to 1.16.1 expiry time placeholders are not working

![image](https://user-images.githubusercontent.com/54243352/88815693-86d9e700-d1b3-11ea-9cf0-c0f9b36fdedd.png)

In 1.15.2 it worked fine look.

![image](https://user-images.githubusercontent.com/54243352/88815661-7e81ac00-d1b3-11ea-952c-b02080302eaf.png)

As you can see, 1.16.1 does not work
![image](https://user-images.githubusercontent.com/54243352/88816083-efc15f00-d1b3-11ea-83dd-f588fcdf387c.png)

Any ideas?

![luu](https://user-images.githubusercontent.com/54243352/91334845-770bed80-e7c7-11ea-8171-76b49c3e068a.png)

![luuu](https://user-images.githubusercontent.com/54243352/91334842-76735700-e7c7-11ea-9b95-1a68fc447a3d.png)

### How to reproduce

1.

**Comment by Andre601** [comment] 2020-08-26 18:09
I don't think this is caused by PlaceholderAPI unless @lucko can show us where this placeholder is handled by his expansion.

But I'm pretty sure this isn't the cause of PlaceholderAPI nor is it in any way related to the version.

Also, please fill out the **entire** template and not just half of it. The points exist for reasons.

**Comment by rosiejane** [comment] 2020-08-26 19:58
@Favorlock 

https://paste.helpch.at/apepeyinig

**Comment by Andre601** [comment] 2021-01-06 15:23
I'll close this for now as this issue didn't receive any updates on the issue and since lucko never responded.

If you're still experiencing this issue, create a new `/papi dump` and try to provide a setup (server used, plugins used, steps to reproduce) to make it possible for us to check.

**Closed by Andre601** 2021-01-06 15:23 UTC
Labels: Type: Issue (Unconfirmed)
