### ISSUE TITLE
Sugestions for expanding commands to target more an one player

### ISSUE THREAD

**Issue by broken1arrow** [PlaceholderAPI/PlaceholderAPI#441] opened 2020-08-16 21:08 UTC
## Feature Request
Add /papi parse all and /papi parse all offline options. 

### Type

- [x] New function for PlaceholderAPI.  
A new function that developers could use.
- [ ] Change to code (Internal).  
Changes to code that won't affect the end-user.
- [ ] Other: 
add more options too commands.
Soo you can target all players online and/or offline too.

### Description
 I use a command like this [console] papi parse %player_Name% %javascript_cooldown_tes1_start% 

But side effect, it only player some activate the command some see the cooldown.

So add option in the command so it can run for all players (if you want it). In this case i use, it activate a permission for 3 hours and give all players online or login a bonus (earn more money or xp etc). 

So not all players can see how long time it left and it give me option to use the placeholder on more places an in deluxemenu.

**Comment by Andre601** [comment] 2020-08-16 23:39
I don't know if this is of any use, but there is the [`/papi bcparse` command](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Commands#papi-bcparse) which parses the placeholders and then broadcasts it (Although when lookking at it does it seem to only target the player you defined)

**Comment by thienbao860** [comment] 2020-08-17 00:57
I don't know about this, but if you stumble upon a player named "all" in one of the servers, it may malfunction

**Comment by broken1arrow** [comment] 2020-08-17 04:34
> I don't know about this, but if you stumble upon a player named "all" in one of the servers, it may malfunction

True, not need bee exactly all, can use a word some not inflict with playername. 

Ower money plugin has all and alloffline, beside playername (so I don't know if it a problem if player has this name).

**Comment by Andre601** [comment] 2020-08-17 10:48
I'm in the process of adding a new parse command called parseall.
Right now would the command get all online players, parse the placeholders withem and send that message to you.

**Comment by broken1arrow** [comment] 2020-08-17 11:17
> I'm in the process of adding a new parse command called parseall.
> Right now would the command get all online players, parse the placeholders withem and send that message to you.

Sounds nice, can not wait to test it out:)

**Comment by Andre601** [comment] 2020-08-19 15:07
So, just to understand this correct: What is the exact goal here?

- Parse the provided String based on the online players and send them the text? Or
- Parse the provided String based on the online players and send them to yourself?

**Comment by broken1arrow** [comment] 2020-08-19 18:02
> 
> 
> So, just to understand this correct: What is the exact goal here?
> 
>     * Parse the provided String based on the online players and send them the text? Or
> 
>     * Parse the provided String based on the online players and send them to yourself?

I run this in deluxmenu [console] papi parse %player_Name% %javascript_cooldown_Miner_start% 
I do like this, but only for player ho activate it. 

The receiving placeholder are %javascript_cooldown_Miner_10800% (some you see in the lore) but it only show the timer for one player not all (rest some see same lore see only 0s). 

This is not 100% correct image (I testing this out, soo don't care it are two similar images).
https://cdn.discordapp.com/attachments/678759670088728617/744619322508574810/test.png

**Comment by broken1arrow** [comment] 2020-08-20 06:11
> 
> 
> So, just to understand this correct: What is the exact goal here?
> 
>     * Parse the provided String based on the online players and send them the text? Or
> 
>     * Parse the provided String based on the online players and send them to yourself?

I think is more like number 1, But is not text i send. It for activate a java scripted timer placeholder. But i guess it almost same thing as send text?

**Comment by Andre601** [comment] 2020-08-20 11:04
> I think is more like number 1, But is not text i send. It for activate a java scripted timer placeholder. But i guess it almost same thing as send text?

I don't really understand what exactly you mean with that.
I right now added a `all` argument to the `bcparse` command, which - instead of just using the executor of the commands for the placeholders - takes every online player and sends them the info based on themself.

I again can't really get what you want to achieve here and I doubt my addition here will change this at all.

**Comment by broken1arrow** [comment] 2020-08-20 11:47
> 
> 
> > I think is more like number 1, But is not text i send. It for activate a java scripted timer placeholder. But i guess it almost same thing as send text?
> 
> I don't really understand what exactly you mean with that.
> I right now added a `all` argument to the `bcparse` command, which - instead of just using the executor of the commands for the placeholders - takes every online player and sends them the info based on themself.
> 
> I again can't really get what you want to achieve here and I doubt my addition here will change this at all.

I´m sorry you don't understand (english is not my native language).

I hope this video explain what i want. I have two accounts running (the to right activate it and left should see same time).
https://youtu.be/IY8W5fvHIfs

**Comment by Andre601** [comment] 2020-08-20 13:32
I see now. This is probably more an issue caused by your javascript and not really something we could solve through PlaceholderAPI.

The whole time did I assume you wanted a parse command to parse for all players or something...

@extendedclip Do you have any additional info on this (i.e. how the Javascript could be changed to not display the countdown lore when the player isn't on cooldown?)
Also, is the PR #442 still a somewhat good idea to add or not really useful? (It would essentially display the broadcasted String of to the player with their info and not the one of the executor)

**Comment by broken1arrow** [comment] 2020-08-20 13:59
> 
> 
> I see now. This is probably more an issue caused by your javascript and not really something we could solve through PlaceholderAPI.
> 
> The whole time did I assume you wanted a parse command to parse for all players or something...
> 
> @extendedclip Do you have any additional info on this (i.e. how the Javascript could be changed to not display the countdown lore when the player isn't on cooldown?)
> Also, is the PR #442 still a somewhat good idea to add or not really useful? (It would essentially display the broadcasted String of to the player with their info and not the one of the executor)

You almost understand what i mean, Is not problem to not display the countdown (you can fix it in deluxmeny really easy).

The problem is the javacript not show time for all players, only player some activate a boost (the boost activate to all players online and even they some login too (if the boost is still active), not only one player).

In short, player A push and start a boost (a goldboost for 3h some example), player B,C,D get same boost, but get no timer (so they don´t know when it end).

**Comment by Andre601** [comment] 2021-01-06 15:20
Closing this issue as it isn't really doable on our end.

Maybe consider looking for a different expansion or a plugin that allows setting and using global cooldowns?

**Closed by Andre601** 2021-01-06 15:20 UTC
Labels: Type: Enhancement

**Comment by broken1arrow** [comment] 2021-01-06 15:55
> Closing this issue as it isn't really doable on our end.
> 
> Maybe consider looking for a different expansion or a plugin that allows setting and using global cooldowns?

I solved the issue tru install luck perms they have placeholder for timed perms. Other payd one we use before has less placeholders and functions. 

Is not exist any expansions, only find one plugin for this and is not get update for long time.
