### ISSUE TITLE
Papi won't start properly 

### ISSUE THREAD

**Issue by matipoirierg** [PlaceholderAPI/PlaceholderAPI#868] opened 2022-08-06 20:22 UTC
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

Plugin won't start properly, after starting the server palceholders won't work, so I have to  manually reload the plugin for them to start working again.

### Expected Behaviour

Boot up normally and all placeholders should work.

### How to Reproduce

Have the following expansions and being on 1.19.2: 
Expancion-husktowns
Expansion-mcmmo
Expansion-server
Expansion-vault
McMMO-Ovewrhaul-Expansion

### `/papi dump` Output

https://paste.helpch.at/ewefuvexis

### Console Log

https://mclo.gs/ydaZP6U

### Errors

https://mclo.gs/cNMDaNF

**Comment by BlitzOffline** [comment] 2022-08-06 20:34
I will mention that I've seen reports of this happening before to other people as well. I've never had it happen to me but here are some logs from other people:

https://paste.helpch.at/aliletibor.sql
https://pastebin.com/n46Wxdsn
https://paste.helpch.at/acugididec.sql
https://paste.helpch.at/dovatagucu.sql

These are just a few I got from the helpchat discord server. So it clearly is a very common issue, but not sure where. hopefully these extra logs can be of a bit more assistance to whoever will look into this.

**Comment by Andre601** [comment] 2022-08-06 21:16
What I notice, is this particular part here:
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getClassLoader()" because "result" is null
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:113) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
```
It seems to somehow mess up the Class loader in the FileUtils maybe?
Or Pufferfish and Purpur changed something in the PluginClassLoader that causes this, since the NPE first points to that PluginClassLoader to give the NPE...

Tho, that are just guesses from my end.

**Comment by Kqliber** [comment] 2022-08-06 21:25
@matipoirierg Is it possible for you to try and replicate this issue using spigot/paper please instead of using pufferfish

**Comment by matipoirierg** [comment] 2022-08-07 19:54
tried latest dev build and the issue is gone

**Comment by Andre601** [comment] 2022-08-07 20:05
> tried latest dev build and the issue is gone

Latest dev build of what? PlaceholderAPI or Server?

**Comment by matipoirierg** [comment] 2022-08-07 20:52
My bad  issue persist, I'll try with paper. I was refering to PAPI.

**Comment by BlitzOffline** [comment] 2022-08-09 00:07
We got another report in the discord server. Its purpur once again: https://paste.helpch.at/tuzukibiwa.sql
Their full message was:

> Good evening - I have a second time error with placeholderapi (dev build 160)
https://paste.helpch.at/tuzukibiwa.sql
> Server restart solves the problem, but it's a second time this month. How can I prevent from that or maybe a fix please?

Waiting for a dump and will edit the message with it when I get it.

**Comment by Andre601** [comment] 2022-08-09 00:19
> We got another report in the discord server. Its purpur once again: https://paste.helpch.at/tuzukibiwa.sql

That error is somewhat different tho.
Most if not all other errors you shared have a `CompletionException <- NullPointerException` combination, while this one is a `CompletionException <- ConcurrentModificationException`

**Comment by Andre601** [comment] 2022-08-09 00:25
Also, there seems to be a possible issue: https://github.com/pufferfish-gg/Pufferfish/blob/ver/1.19/patches/api/0003-Ignore-lookups-if-closed.patch

This patch on Pufferfish (Which by extension was added to Purpur) is probably the cause of these issues.
Purpur devs told me they may remove this patch, so at least there will the plugin (hopefully) work again in the near future.

**Comment by kev626** [comment] 2022-08-09 00:33
Removing this patch breaks flare. Why is PAPI trying to look up classes from unloaded plugins?

**Comment by Andre601** [comment] 2022-08-09 00:41
> Removing this patch breaks flare. Why is PAPI trying to look up classes from unloaded plugins?

From my understanding: It doesn't.

PlaceholderAPI's FileUtils creates a URL from whatever File it is given - which in this case is the Expansion Jar file - and with the `PlaceholderExpansion.class` as its parent.

So technically should it not "try to look up other plugin classes"
Perhaps it's an unwanted side effect of Expansions that use instances of a Plugin in their register method or smth?

Either way, that's just my basic understanding, so I can obviously be wrong.

Meanwhile, could you try out the latest Purpur patches (Build 1754): https://purpurmc.org/downloads

**Comment by kev626** [comment] 2022-08-09 00:56
Just did some more analysis and root-cause'd the issue. [This](https://github.com/pufferfish-gg/Pufferfish/commit/4882a952ea5fcb12cf6f8f164a8010fc2f85a25c) should fix the issue.

**Comment by Andre601** [comment] 2022-08-09 01:04
> Just did some more analysis and root-cause'd the issue. [This](https://github.com/pufferfish-gg/Pufferfish/commit/4882a952ea5fcb12cf6f8f164a8010fc2f85a25c) should fix the issue.

Not sure where swapping one exception out for another really fixes the issue, considering the `FileUtils.findClass` method is used like this
```java
try {
    final Class<? extends PlaceholderExpansion> expansionClass = FileUtil.findClass(file, PlaceholderExpansion.class);
    
    // Do other stuff
} catch (final VerifyError ex) {
    Msg.severe("Failed to load expansion class %s (is a dependency missing?", file.getName() + ')');
    Msg.severe("Cause: %s %s", ex.getClass().getSimpleName(), ex.getMessage());
    return null;
} catch (Exception ex) {
    throw new CompletionException(ex); // This would still be thrown here.
}
```

**Comment by kev626** [comment] 2022-08-09 01:09
> Not sure where swapping one exception out for another really fixes the issue, considering the FileUtils.findClass method is used like this

It fixes it further up the chain in the big long convoluted maze that is classloader inheritance. Returning `null` results in an NPE being thrown later on. But a `ClassNotFoundException` exception is caught, handled, and eventually re-thrown as a `NoClassDefFoundError`, which is caught by `FileUtils.findClass`. Thus solving the root cause of the problem.

You can see that if the `result == null` branch is taken, then the only possible outcomes of the method are returning a non-null object, a `ClassNotFoundException`, or a `IllegalStateException` (which is intended to bubble up).

**Comment by matipoirierg** [comment] 2022-08-09 16:42
> Just did some more analysis and root-cause'd the issue. [This](https://github.com/pufferfish-gg/Pufferfish/commit/4882a952ea5fcb12cf6f8f164a8010fc2f85a25c) should fix the issue.

can confirm it fixed it, thanks.

**Comment by Andre601** [comment] 2022-08-11 22:15
Since OP said this is fixed am I closing it. Thanks to Pufferfish and PurpurMC devs for implementing fixes.

**Closed by Andre601** 2022-08-11 22:15 UTC
Labels: Type: Issue (Unconfirmed)
