### ISSUE TITLE
Placeholder not show

### ISSUE THREAD

**Issue by Shhishsh** [PlaceholderAPI/PlaceholderAPI#813] opened 2022-03-11 22:53 UTC
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.

### Type

Plugin Bug

### What happens?

Hi, I have the latest version of PlaceholderAPI and Featherboard as a plugin on my server. I run my PaperSpigot 1.17 server and versions 1.16 and below don't see placeholders.

### Expected Behaviour

Show version 1.16 below placeholder featherboard

### How to Reproduce

idk

### `/papi dump` Output

https.a

**Comment by whoatemycookie8297** [comment] 2022-04-02 22:40
Hello, 
I have this issue too where FeatherBoard won't hook into placeholders at all under 1.18.2 (to my knowledge) 

Here is a Dump from PAPI
https://paste.helpch.at/emocuhifaq
![papi](https://user-images.githubusercontent.com/37166043/161403658-6c3c5f45-2da0-4ec6-90e7-336e5597f04e.png)

Not sure if this is a FeatherBoard issue or a Papi issue.

**Comment by BlitzOffline** [comment] 2022-04-02 22:48
> Hello, I have this issue too where FeatherBoard won't hook into placeholders at all under 1.18.2 (to my knowledge)
> 
> Here is a Dump from PAPI [paste.helpch.at/emocuhifaq](https://paste.helpch.at/emocuhifaq) ![papi](https://user-images.githubusercontent.com/37166043/161403658-6c3c5f45-2da0-4ec6-90e7-336e5597f04e.png)
> 
> Not sure if this is a FeatherBoard issue or a Papi issue.

it just seems like your expansions are not loading. What I assume happens is that you have a broken expansion that breaks and takes down the expansion loader with it and your expansion's don't load. I recommend you send your startup log in a paste bin for us to take a look at it.

**Comment by whoatemycookie8297** [comment] 2022-04-02 23:01
> > Hello, I have this issue too where FeatherBoard won't hook into placeholders at all under 1.18.2 (to my knowledge)
> > Here is a Dump from PAPI [paste.helpch.at/emocuhifaq](https://paste.helpch.at/emocuhifaq) ![papi](https://user-images.githubusercontent.com/37166043/161403658-6c3c5f45-2da0-4ec6-90e7-336e5597f04e.png)
> > Not sure if this is a FeatherBoard issue or a Papi issue.
> 
> it just seems like your expansions are not loading. What I assume happens is that you have a broken expansion that breaks and takes down the expansion loader with it and your expansion's don't load. I recommend you send your startup log in a paste bin for us to take a look at it.  


So, I ended up finding an error for an expansion (ChatReaction), went ahead and deleted it. Still no change
https://pastebin.com/p87Lv7vs (the expansion error)

Startup log: https://pastebin.com/kL3W8f4U (after removing chat reaction expansion)

**Comment by Andre601** [comment] 2022-04-02 23:22
@whoatemycookie8297

There are a few things I noticed looking through the log:

- Plugins that throw exceptions:
  - PacketListenerAPI
  - AAC5
  - Orebfuscator
  - WorldGuard
  - MCMMO
  - StaffFacilities
  - PlayerWarps
  - CMILib
  - Jobs
- Other issues:
  - TimeIsMoney reports a configuration issue
  - PointService seems to be not a valid expansion, causing an exception. Report this to the dev.

On a personal note:
Please do not use leaked resources.
Using leaked resources is disgusting as you basically steal software that some people spend a lot of time working on. While I can't stop you from doing this will I not give any future support here whatsoever as it goes against my personal moral code.
Whether the others will help you is up to them.

I found the following leaked resources:

- Citizens
- StaffFacilities

**Comment by whoatemycookie8297** [comment] 2022-04-02 23:49
> @whoatemycookie8297
> 
> There are a few things I noticed looking through the log:
> 
> * Plugins that throw exceptions:
>   
>   * PacketListenerAPI
>   * AAC5
>   * Orebfuscator
>   * WorldGuard
>   * MCMMO
>   * StaffFacilities
>   * PlayerWarps
>   * CMILib
>   * Jobs
> * Other issues:
>   
>   * TimeIsMoney reports a configuration issue
>   * PointService seems to be not a valid expansion, causing an exception. Report this to the dev.
> 
> On a personal note: Please do not use leaked resources. Using leaked resources is disgusting as you basically steal software that some people spend a lot of time working on. While I can't stop you from doing this will I not give any future support here whatsoever as it goes against my personal moral code. Whether the others will help you is up to them.
> 
> I found the following leaked resources:
> 
> * Citizens
> * StaffFacilities

Hey, thank you for the help, and thanks very much for letting me know about those 2 plugins. My buddy that's helping me provided those for me and never realized it. I'll go and purchase them here in a little bit. Understandable if you don't want to offer any support. I'll definitely go ahead look into those plugins that are throwing exceptions. Thanks very much for the help you all have provided. When I go fix those issues and the problem still exists I'll come back here and report my results.

**Comment by PikaMug** [comment] 2022-05-02 00:45
It's worth noting that Citizens is not a leaked resource. They provide a link to free builds on their [resource page](https://www.spigotmc.org/resources/citizens.13811/) and make it clear that paying for releases is entirely optional.

**Comment by Starmism** [comment] 2022-05-02 01:02
> It's worth noting that Citizens is not a leaked resource. They provide a link to free builds on their [resource page](https://www.spigotmc.org/resources/citizens.13811/) and make it clear that paying for releases is entirely optional.

It's also worth noting that in that startup log, it lists 
`[18:59:11] [Server thread/INFO]: [Citizens] [STDOUT] [Citizens] Leaked by YOURNAME @ BlackSpigot.com`.
Even if there are no moral dilemmas to think about, using a jar leaked by someone often means they made other changes than just possible DRM removal, which can drastically compromise the safety of any server.

**Comment by BlitzOffline** [comment] 2022-05-02 07:14
> It's worth noting that Citizens is not a ~leaked~ stolen resource. They provide a link to free builds on their [resource page](https://www.spigotmc.org/resources/citizens.13811/) and make it clear that paying for releases is entirely optional.

Unfortunately people leak even free resources or rather freemium ones. Citizens is a good example of this. They mostly do this because its very easy to get someone that doesn't read the spigot page to just google "<resource> bl*******ot" and get them to download a compromised jar which might just give them full access to the server. Even if the resource is free for download, its not free for redistribution(I might be technically wrong here. depends on the license I guess) especially not on a well known leaking website. So that still goes against a lot of rules/laws + leaves the server to be compromised very easily.

**Comment by xIsm4** [comment] 2022-07-06 17:51
True, an customer reported m,e that same issue of placeholders withLuckPerms, by downgrading worked is an Papi issue ig.

**Comment by TechieBlort** [comment] 2022-08-30 19:14
I am also having this same issue. but on a 1.19.2 server with Via backwards back to 1.17.x listed here: https://paste.helpch.at/qidupirusi Server software being Purpur. I have also replicated the same issue on 1.19.2 paper Spigot listed here: https://paste.helpch.at/agegaqusaf I don't know if this will help your diagnostics but I have only been getting this issue with 1.19.x servers we had a 1.18.x server that didn't have this issue. Hope it helps to resolve this :) It is worth noting that I am also using 1.19.2 to join the server as well as the server software associated with it.

**Comment by Andre601** [comment] 2022-08-30 19:20
> I am also having this same issue. but on a 1.19.2 server with Via backwards back to 1.17.x listed here: https://paste.helpch.at/qidupirusi Server software being Purpur. I have also replicated the same issue on 1.19.2 paper Spigot listed here: https://paste.helpch.at/agegaqusaf I don't know if this will help your diagnostics but I have only been getting this issue with 1.19.x servers we had a 1.18.x server that didn't have this issue. Hope it helps to resolve this :) It is worth noting that I am also using 1.19.2 to join the server as well as the server software associated with it.

I am pretty sure you can blame ViaBackwards on this one.
After all has 1.19.1+ had significant changes to chats that aren't the same on 1.18 or older.
So if it works without ViaBackwards then you know the cause here.

**Comment by TechieBlort** [comment] 2022-08-30 19:28
> > I am also having this same issue. but on a 1.19.2 server with Via backwards back to 1.17.x listed here: https://paste.helpch.at/qidupirusi Server software being Purpur. I have also replicated the same issue on 1.19.2 paper Spigot listed here: https://paste.helpch.at/agegaqusaf I don't know if this will help your diagnostics but I have only been getting this issue with 1.19.x servers we had a 1.18.x server that didn't have this issue. Hope it helps to resolve this :) It is worth noting that I am also using 1.19.2 to join the server as well as the server software associated with it.
> 
> I am pretty sure you can blame ViaBackwards on this one. After all has 1.19.1+ had significant changes to chats that aren't the same on 1.18 or older. So if it works without ViaBackwards then you know the cause here.

unfortunately the same issue is still occurring on my local test server. dump after removing a broken placeholder thing on my local server due to a missing plugin and via backwards: https://paste.helpch.at/ivutatacuj

**Comment by Andre601** [comment] 2022-08-30 19:33
> unfortunately the same issue is still occurring on my local test server. dump after removing a broken placeholder expansion on my local server due to a missing plugin and via backwards: https://paste.helpch.at/ivutatacuj also appears to still occur even after removing ViaVersion itself.

The dump itself doesn't help us at all understanding the issue.
Please open a separate issue to track this properly as I doubt this is related to this issue here.

**Comment by Andre601** [comment] 2024-05-19 16:17
Given the age of this issue will I close it. Should the issue still be present after such a long time, let us know with further details.

**Closed by Andre601** 2024-05-19 16:17 UTC
Labels: Problem: More info required, Type: Issue (Unconfirmed)
