### ISSUE TITLE
Gringgots Placeholder

### ISSUE THREAD

**Issue by Darklom** [PlaceholderAPI/PlaceholderAPI#308] opened 2020-05-09 02:40 UTC
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

An error comes up throughout the day
https://pastebin.com/ujRfX50j

### Expected behaviour
> What should PlaceholderAPI do?

No error

### Actual behaviour
> What does PlaceholderAPI actually do?

Same error code throughout the day

### How to reproduce
> What steps did you made, to get this bug?

1. It appears to have an issue with Gringotts (potentially something to do with the money?)  Latest dev version of Gringotts

**Comment by aBooDyy** [comment] 2020-05-24 22:50
Hello there,

It seems like the issue is coming from Gringgots plugin. I suggest you contact the author of this plugin and provide them the error.

Will close the issue as it's not from to PlaceholderAPI plugin.

Good luck,
aBooDyy

**Closed by aBooDyy** 2020-05-24 22:50 UTC
