### ISSUE TITLE
broken with Paper with CB packge relocation

### ISSUE THREAD

**Issue by YuanYuanOwO** [PlaceholderAPI/PlaceholderAPI#1052] opened 2024-03-22 12:11 UTC
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin Bug

### What happens?

got error from placeholderapi

### Expected Behaviour

The plugin is running

### How to Reproduce

1. use this version for papermc(https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/)
2. try to running the plugin

### `/papi dump` Output

N/A

### Errors

https://paste.helpch.at/awuduvonut.css

**Comment by Andre601** [comment] 2024-03-22 17:49
Duplicate of #1034

**Closed by Andre601** 2024-03-22 17:49 UTC
Labels: Type: Issue (Unconfirmed)
