### ISSUE TITLE
Skript Expansion will not download since September

### ISSUE THREAD

**Issue by EthsMC** [PlaceholderAPI/PlaceholderAPI#518] opened 2020-12-27 20:24 UTC
### Issue

The skript expansion will not load, has been an issue since early September of 2020

As you can see, after installing the skript expansion and reloading, it doesnt load any expansions, but downloading an expansion like Player, it works just as its supposed to
![image](https://user-images.githubusercontent.com/69118918/103179170-2a105480-4857-11eb-87c4-a01eaf8b5139.png)

### Expected behaviour

It should load skript as an expansion but after reloading PAPI, it just doesnt load it

### Actual behaviour

It allows you to use skript placeholders in PAPI supporting plugins, Extremely important thing to have on a platform where skript is the main source of customizability

### How to reproduce

1.  Just try to download the skript expansion and reload papi

### `/papi dump` output

https://paste.helpch.at/linojifiqe

**Comment by Andre601** [comment] 2020-12-27 21:47
Any errors in the console when reloading?

**Comment by EthsMC** [comment] 2020-12-27 22:10
Looking into this, seems to only be an issue with the Minehut version, no errors in the console log

Will contact minehut with a link to this thread

**Comment by Andre601** [comment] 2020-12-27 22:40
Yeah. That is the downside of using hosts like MineHut and nothing we really can do much about.

**Comment by EthsMC** [comment] 2020-12-27 22:43
Yea i only use minehut cuz its free players and money

**Comment by Andre601** [comment] 2021-01-06 15:40
I'm closing this as it is most likely caused by MineHut

**Closed by Andre601** 2021-01-06 15:40 UTC
Labels: Type: Issue (Unconfirmed)
