### ISSUE TITLE
Skript addon will not install

### ISSUE THREAD

**Issue by EthsMC** [PlaceholderAPI/PlaceholderAPI#566] opened 2021-02-13 17:17 UTC
### Issue

Skript addon will not install, You can run the command and it says it installs but once you reload the plugin It just doesnt load

### Expected behaviour

It should install and load once you reload the plugin

### Actual behaviour

It downloads the addon in the folder, but it does not load it no matter what

### How to reproduce

1.  /papi ecloud download Skript
2.  /papi reload
3. Addon does not load so I cant use skript variables 

### `/papi dump` output

https://paste.helpch.at/zohabineda

**Comment by Andre601** [comment] 2021-02-13 17:22
duplicate of #535

**Closed by Andre601** 2021-02-13 17:22 UTC
