### ISSUE TITLE
PlaceholderAPI 1.19.3 support

### ISSUE THREAD

**Issue by LucidAPs** [PlaceholderAPI/PlaceholderAPI#899] opened 2022-12-15 06:52 UTC
### Confirmation

- [X] My issue isn't already found on the Issue tracker.
- [X] My issue is about **PlaceholderAPI** and not any expansion or external plugin
- [X] The issue isn't already fixed in a Spigot Release or Development Build.
- [X] The [Common Issues](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Common-Issues) page doesn't mention this issue.

### Type

Plugin/Server Incompatability

### What happens?

[08:44:03] [Server thread/ERROR]: [PlaceholderAPI] Failed to load class files of expansion.
java.util.concurrent.CompletionException: java.lang.IllegalStateException: zip file closed
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:428) ~[PlaceholderAPI-2.11.3-DEV-160.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:189) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:129) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:237) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:574) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.clip.placeholderapi.util.FileUtil.findClass(FileUtil.java:62) ~[PlaceholderAPI-2.11.3-DEV-160.jar:?]
	at me.clip.placeholderapi.expansion.manager.LocalExpansionManager.lambda$findExpansionInFile$7(LocalExpansionManager.java:405) ~[PlaceholderAPI-2.11.3-DEV-160.jar:?]
	... 7 more

### Expected Behaviour

1.19.3 support

### How to Reproduce

1.19.3 support

### `/papi dump` Output

1.19.3 support

**Comment by xF3d33** [comment] 2022-12-26 22:14
![image](https://user-images.githubusercontent.com/67204462/209585995-3b4efa06-e48e-445c-b100-d7b832398757.png)
i also have this problem, but it doesn't happen everytime. 

/papi reload fixes this

**Comment by iGabyTM** [comment] 2023-02-05 22:05
@LucidAPs @xF3d33 is possible to list the plugins that you are using and also the build number of purpur / paper?

**Comment by SlimeDog** [comment] 2023-02-26 21:45
This issue occurs frequently with Paper 1.19.3-420, and has since many previous releases.
```
> papi list
[13:42:26 INFO]: A total of 32 placeholder hook(s) are active: 
atr, bentobox, biomeremap, bskyblock, citizensplaceholder, cmil, combatlogx, coordinatetool, deluxemenus, disease
essentials, extrahardmode, frp, level, luckperms, multiverse, plan, player, pyroweatherpro, quests
residence, server, shortcut, spark, stat, statistic, str, thirst, treefeller, vault
wesv, worldguard
> papi ecloud list installed
[13:42:37 INFO]: Installed Expansions
     Name            Author   Verified  Version  
-------------------------------------------------
1.   CoordinateTool  vk2gpz   Y         3.5.3    
2.   Essentials      clip     Y         1.5.2    
3.   LuckPerms       luck     Y         5.4-R2   
4.   Multiverse      clip     Y         1.0.1    
5.   Player          clip     Y         2.0.4    
6.   Quests          pikamug  Y         1.6      
7.   Server          clip     Y         2.6.1    
8.   Statistic       clip     Y         2.0.1    
9.   Thirst          cj89898  Y         1.2.1    
10.  Vault           clip     Y         1.8.1    
11.  WorldGuard      clip     Y         1.4.2    
12.  str             silence  Y         1.0.0 
```
Note that Disease is not included in the latter list, enough though
```
$ ls -1 plugins/PlaceholderAPI/expansions/
DiseasePlaceholders-0.0.2.jar
Expansion-LuckPerms-5.4-R2.jar
Expansion-Multiverse-1.0.1.jar
Expansion-Quests-1.6.jar
Expansion-str-1.0.0.jar
Expansion-Thirst-1.2.1.jar
Expansion-Vault-1.8.1.jar
PAPI-Expansion-Essentials-1.5.2.jar
PAPI-Expansion-Player-2.0.4.jar
PAPI-Expansion-Server-2.6.1.jar
PAPI-Expansion-Statistic-2.0.1.jar
Shortcut-1.2.0.jar
WorldGuard-Expansion-1.4.2.jar
```
All up-to-date.

**Comment by SlimeDog** [comment] 2023-03-01 01:22
Among other things, it would be useful if the error messages identified the expansion that caused the issue.

**Comment by SlimeDog** [comment] 2023-03-01 19:21
After a fair amount of isolation testing, it looks like this issue is caused by PAPI-Expansion-Server-2.6.1.

Seee https://github.com/PlaceholderAPI/Server-Expansion/issues/49

**Comment by BlitzOffline** [comment] 2023-03-01 19:24
> It would be useful if the error message identified the expansion that caused the issue.

I definitely agree. I've asked for this feature before. While it is true that each expansion should deal with it's own problems, I think PlaceholderAPI should probably safely load each expansion and if it fails, it shouldn't break the entire loader but instead it should catch the exception, log it with more information such as expansion it is coming from and then continue loading the other expansions. Currently if an expansion throws an exception on load, all other expansions that come after, won't load either.

**Comment by SlimeDog** [comment] 2023-03-01 19:29
Looks to be fixed in PAPI-Expansion-Server 2.6.2 and a lot of other clip expansions.

**Comment by iGabyTM** [comment] 2023-03-01 19:30
Yeah, the difference between 2.6.1 and 2.6.2 is that the former version used some external library for cache, interesting 🤔

**Comment by SlimeDog** [comment] 2023-03-01 20:10
There remains the issue of PAPI identifying an expansion that causes an issue.

**Comment by iGabyTM** [comment] 2023-03-17 19:57
@SlimeDog are you still able to replicate this exception? https://github.com/PlaceholderAPI/PlaceholderAPI/issues/899#issuecomment-1365485606

**Comment by SlimeDog** [comment] 2023-03-17 20:03
The issue with Server expansion was resolved over there. However, the issue with PAPI not identifying the offending expansion remains.

**Comment by iGabyTM** [comment] 2023-03-17 20:12
Yeah, I'm working on that, but I need a server that has that `zip file closed` problem because for the sake of god I can not seem to be able to reproduce it 🤐

**Comment by SlimeDog** [comment] 2023-03-17 22:41
I think you might be able to reproduce it if you downgrade to
Paper 1.19.3-420
PlacehoIderAPI-2.11.2-DEV-160
PAPI-Expansion-Server-2.6.1

**Comment by iGabyTM** [comment] 2023-03-18 09:00
No luck @SlimeDog, please let us know if you can reproduce this with papi 2.11.3

**Comment by SlimeDog** [comment] 2023-03-18 13:12
I can reliably reproduce it, as described in https://github.com/PlaceholderAPI/Server-Expansion/issues/49

**Comment by iGabyTM** [comment] 2023-03-18 13:26
Do you think you can zip the files and send them over? @SlimeDog

**Comment by SlimeDog** [comment] 2023-03-18 13:30
I don't see why it matters. The issue is resolved with updated PAPI-Expansion-Server-2.6.2.

**Comment by iGabyTM** [comment] 2023-03-18 13:32
Because other users are having a similar issue and it is not caused by the server expansion. I need a way to replicate the issue so I can look for a fix.

**Comment by SlimeDog** [comment] 2023-03-18 13:33
Sorry, I cannot share a complete server.

**Comment by iGabyTM** [comment] 2023-03-18 13:33
Understandable, I thought it is a test server.

**Comment by Andre601** [comment] 2023-10-04 10:20
Pretty sure this issue is no longer relevant?
Or are there still issues with this particular version?

**Closed** 2024-05-19 16:15 UTC
Labels: Type: Issue (Unconfirmed)
