### ISSUE TITLE
Placeholders "vault_prefix_color" & "vault_suffix_color" do not support hex color codes

### ISSUE THREAD

**Issue by tjalp** [PlaceholderAPI/PlaceholderAPI#489] opened 2020-10-02 14:56 UTC
### Issue
Whenever using the placeholder `vault_prefix_color` or `vault_suffix_color` it returns the last color code in a hex color code such as `&x&f&f&4&2&3&f` (this would return `&f` since it's the last color code).

### Expected behaviour
It should return the valid hex color code.

### Actual behaviour
It returns the last color code in a hex color code such as `&x&f&f&4&2&3&f`

### How to reproduce
Just use the placeholder using /papi parse me %vault_prefix_color% with a hex color as the prefix.

### `/papi dump` output
https://paste.helpch.at/utubememoy

**Comment by Andre601** [comment] 2020-10-02 17:05
Now when looking at it is it perhaps caused by PlaceholderAPI not using the right ChatColor lib to parse.
Sorry for that message. You can ignore it.

**Comment by Andre601** [comment] 2022-04-02 23:04
I'm closing this because in a future release will PlaceholderAPI no longer parse colors when using the `setPlaceholders` methods.

It shouldn't be the job of a Placeholder Util to also parse colors and if people want that in their expansions should it be added by them.

If anything changes on this topic will I inform you here about this.

**Closed by Andre601** 2022-04-02 23:04 UTC
Labels: Type: Issue (PlaceholderAPI), Hacktober
